In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3, 3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0, 1, 2], index = ['T', 'U', 'V'])
ser2 = Series([3, 4], index = ['X', 'Y'])

ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2], axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
df1 = DataFrame(np.random.randn(4, 3), columns = ['X', 'Y', 'Z'])
df1

X         Y         Z
0 -1.250919  0.548625 -1.539937
1  0.717675  1.152902  1.349477
2  0.983910 -0.329607 -1.021923
3 -1.381682 -0.800277  0.328820

In [17]:
df2 = DataFrame(np.random.randn(3, 3), columns = ['Y', 'Q', 'X'])
df2

Y         Q         X
0  0.820994 -0.144324 -0.557720
1 -0.365021 -0.620883 -0.233143
2 -1.963266  0.847249  0.963946

In [20]:
pd.concat([df1, df2], ignore_index = True)

X         Y         Z         Q
0 -1.250919  0.548625 -1.539937       NaN
1  0.717675  1.152902  1.349477       NaN
2  0.983910 -0.329607 -1.021923       NaN
3 -1.381682 -0.800277  0.328820       NaN
4 -0.557720  0.820994       NaN -0.144324
5 -0.233143 -0.365021       NaN -0.620883
6  0.963946 -1.963266       NaN  0.847249