In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame(np.arange(16).reshape(4, 4))

In [3]:
blender = np.random.permutation(4)

In [4]:
blender

array([3, 1, 0, 2])

In [5]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
df.take(blender)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [7]:
box = np.array([1, 2, 3])

In [8]:
shaker = np.random.randint(0, len(box), size = 10)
shaker

array([1, 2, 0, 2, 0, 1, 2, 0, 1, 2])

In [9]:
box.take(shaker)

array([2, 3, 1, 3, 1, 2, 3, 1, 2, 3])