In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])

In [4]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [5]:
arr1 + 5

array([[ 6,  7,  8,  9],
       [13, 14, 15, 16]])

In [6]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1 * np.array([[3, 4, 5, 6], [6, 5, 4, 3]])

array([[ 3,  8, 15, 24],
       [48, 45, 40, 33]])

In [9]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [ ]:
round(1 / arr1,)