In [2]:
import numpy as np

In [3]:
my_list1 = [1, 2, 3, 4]

In [5]:
my_list1

[1, 2, 3, 4]

In [6]:
my_array1 = np.array(my_list1)

In [7]:
my_array1

array([1, 2, 3, 4])

In [8]:
type(my_array1)

numpy.ndarray

In [9]:
my_list2 = [11, 22, 33, 44]

In [10]:
my_lists = [my_list1, my_list2]

In [11]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array2 = np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
my_array2.shape()

TypeError: 'tuple' object is not callable

In [15]:
my_array2.shape

(2, 4)

In [16]:
my_array2.dtype

dtype('int64')

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(2, 5)

TypeError: Cannot interpret '5' as a data type

In [19]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.empty([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(3, 8, 10)

array([3])

In [25]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [27]:
np.empty([5, 3])

array([[4.65300379e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])