In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-0.29562651,  1.33304666, -0.98307236,  0.22663365,  1.34788698,
        1.43711342, -0.09378997, -0.10125566,  2.25271049, -0.83788083])

In [9]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [10]:
B = np.random.randn(10)
B

array([-1.67668953, -2.20962361,  1.8068303 , -0.15114149, -1.65304015,
       -1.43130359,  1.3207116 , -0.22223935,  1.0957618 , -1.14387292])

In [11]:
np.add(A, B)

array([-1.97231603, -0.87657695,  0.82375794,  0.07549216, -0.30515317,
        0.00580983,  1.22692163, -0.32349501,  3.34847229, -1.98175375])

In [12]:
np.maximum(A, B)

array([-0.29562651,  1.33304666,  1.8068303 ,  0.22663365,  1.34788698,
        1.43711342,  1.3207116 , -0.10125566,  2.25271049, -0.83788083])

In [13]:
np.minimum(A, B)

array([-1.67668953, -2.20962361, -0.98307236, -0.15114149, -1.65304015,
       -1.43130359, -0.09378997, -0.22223935,  1.0957618 , -1.14387292])